### ISSUE TITLE
[error] Architecture Doesn't Consistently Work

### ISSUE THREAD

**Issue by jbitton** [SudarshiniTyagi/DatingGameArchitecture#1]
Hi there!

Nice architecture, wonder where you got the setup from ;)

Anyway, every so often, the architecture throws a `JSONDecodeError`. Here is my stacktrace:

```
10-16-240-105:DatingGameArchitecture nokogiri$ python3.6 run_game.py 25
Waiting on port 5000 for players...
Player {'n': 25}
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_game.py", line 15, in init_matchmaker
    player = MatchMaker(name=name)
  File "/Users/nokogiri/Documents/NYU/classes@nyu/heuristic problem solving/zach-hps/8_Dating/DatingGameArchitecture/clients/matchmaker_client.py", line 10, in __init__
    game_info = json.loads(self.client.receive_data(size=32368))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4479 (char 4478)
Traceback (most recent call last):
  File "run_game.py", line 36, in <module>
    main()
  File "run_game.py", line 33, in main
    controller = GameServer(n)
  File "/Users/nokogiri/Documents/NYU/classes@nyu/heuristic problem solving/zach-hps/8_Dating/DatingGameArchitecture/dating_server.py", line 29, in __init__
    self.accept_player_connections()
  File "/Users/nokogiri/Documents/NYU/classes@nyu/heuristic problem solving/zach-hps/8_Dating/DatingGameArchitecture/dating_server.py", line 37, in accept_player_connections
    self.play_game()
  File "/Users/nokogiri/Documents/NYU/classes@nyu/heuristic problem solving/zach-hps/8_Dating/DatingGameArchitecture/dating_server.py", line 157, in play_game
    self.matchmaker_idx
  File "/Users/nokogiri/Documents/NYU/classes@nyu/heuristic problem solving/zach-hps/8_Dating/DatingGameArchitecture/dating_server.py", line 42, in timed_request
    vector = json.loads(self.server.receive_from(client_idx))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I made no changes to any of the files. The error isn't always reproducible which may make it harder to debug. I would suggest to try out various values until it occurs. (it most consistently happens with `n=25` though I tried 25, 50, 75, 100, and 200).

Thanks in advance!

**Comment by samcoolidge** [comment]
Thanks for the email, trying to debug now.

**Comment by herbertli** [comment]
I think this Decode error happens due to some sort of race-condition with the server. During the first competition (nim) my partner I tried C++, and we ran into issues if our client sent data too quickly.
